import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Facebook Clone",
  description: "Generated by create next app",
};

// <meta name="google-site-verification" content="gaNtIh2Feu2U0vEXw0We4OkBh2g7GCuJTHeIalJcBTA" />

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="google-site-verification" content="gaNtIh2Feu2U0vEXw0We4OkBh2g7GCuJTHeIalJcBTA" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="bg-[#f0f2f5]">
              <div className="w-full flex justify-center py-5 bg-red-500 text-white">
                <strong>Warning:</strong> This is a personal project and not the official Facebook website. Please do not share any personal information. Use the provided email and password to log in instead.
              </div>
              <Header />
              {children}
          </div>
      </body>
    </html>
  );
}
